name: EzObserver
version: ${project.version}
main: top.mc_plfd_host.ezobserver.EzObserver
api-version: 1.20
folia-supported: true
author: Kush_ShuL
description: 反违规物品插件 - 监听物品移动并检测违规附魔和属性修饰符 (支持Folia)

commands:
  ezobserver:
    description: EzObserver 管理命令
    usage: /ezobserver <reload|status|help>
    aliases: [ezo, ezobs]
    permission: ezobserver.admin

permissions:
  ezobserver.admin:
    description: 允许使用 EzObserver 管理命令
    default: op
  ezobserver.bypass:
    description: 绕过物品检测
    default: false